/* eslint-disable */
// GENERATED by scripts/ocr-checksums.mjs — do not edit.
// Digests are specific to tessdata tag 4.1.0. Re-run after changing it.

export interface PackDigest {
  sha256: string
  size: number
}

/** Keyed `${code}:${set}`. A missing entry means the pack cannot be installed. */
export const PACK_DIGESTS: Record<string, PackDigest> = {
  'spa:fast': { sha256: '6f2e04d02774a18f01bed44b1111f2cd7f3ba7ac9dc4373cd3f898a40ea6b464', size: 2294433 },
  'spa:best': { sha256: 'e2c1ffdad8b30f26c45d4017a9183d3a7f9aa69e59918be4f88b126fac99ab2c', size: 13570187 },
  'fra:fast': { sha256: 'ced037562e8c80c13122dece28dd477d399af80911a28791a66a63ac1e3445ca', size: 1130365 },
  'fra:best': { sha256: '907743d98915c91a3906dfbf6e48b97598346698fe53aaa797e1a064ffcac913', size: 3972885 },
  'deu:fast': { sha256: '19d219bbb6672c869d20a9636c6816a81eb9a71796cb93ebe0cb1530e2cdb22d', size: 1525436 },
  'deu:best': { sha256: '8407331d6aa0229dc927685c01a7938fc5a641d1a9524f74838cdac599f0d06e', size: 8628461 },
}

export function digestFor(code: string, set: 'fast' | 'best'): PackDigest | undefined {
  return PACK_DIGESTS[`${code}:${set}`]
}
