/* eslint-disable */
// GENERATED by scripts/ocr-checksums.mjs — do not edit.
// Digests are specific to tessdata tag 4.1.0. Re-run after changing it.

export interface PackDigest {
  sha256: string
  size: number
}

/** Keyed `${code}:${set}`. A missing entry means the pack cannot be installed. */
export const PACK_DIGESTS: Record<string, PackDigest> = {
  'eng:fast': { sha256: '7d4322bd2a7749724879683fc3912cb542f19906c83bcc1a52132556427170b2', size: 4113088 },
  'eng:best': { sha256: '8280aed0782fe27257a68ea10fe7ef324ca0f8d85bd2fd145d1c2b560bcb66ba', size: 15400601 },
  'spa:fast': { sha256: '6f2e04d02774a18f01bed44b1111f2cd7f3ba7ac9dc4373cd3f898a40ea6b464', size: 2294433 },
  'spa:best': { sha256: 'e2c1ffdad8b30f26c45d4017a9183d3a7f9aa69e59918be4f88b126fac99ab2c', size: 13570187 },
  'fra:fast': { sha256: 'ced037562e8c80c13122dece28dd477d399af80911a28791a66a63ac1e3445ca', size: 1130365 },
  'fra:best': { sha256: '907743d98915c91a3906dfbf6e48b97598346698fe53aaa797e1a064ffcac913', size: 3972885 },
  'deu:fast': { sha256: '19d219bbb6672c869d20a9636c6816a81eb9a71796cb93ebe0cb1530e2cdb22d', size: 1525436 },
  'deu:best': { sha256: '8407331d6aa0229dc927685c01a7938fc5a641d1a9524f74838cdac599f0d06e', size: 8628461 },
  'por:fast': { sha256: 'c4932b937207a9514b7514d518b931a99938c02a28a5a5a553f8599ed58b7deb', size: 1982756 },
  'por:best': { sha256: '711de9dbb8052067bd42f16b9119967f30bada80d57e2ef24f65d09f531adb04', size: 8159939 },
  'ita:fast': { sha256: 'b8f89e1e785118dac4d51ae042c029a64edb5c3ee42ef73027a6d412748d8827', size: 2701314 },
  'ita:best': { sha256: '8df9c89176fb93f56bf4b2d4ede04c01c1f31d4b7697fbd76cc336df700f3f38', size: 8863635 },
  'nld:fast': { sha256: 'ced0e5e046a84c908a6aa7accbef9a232c4a5d9a8276691b81c6ee64d02963f6', size: 6050296 },
  'nld:best': { sha256: '92e7a1ad4bf8082e268de57c7823316ec024935702c6ed2a1e473b3a071aa733', size: 8903736 },
  'pol:fast': { sha256: 'c4476cdbc0e33d898d32345122b7be1cbf85ace15f920f06c7714756e1ef79b2', size: 4765518 },
  'pol:best': { sha256: 'e80cc4cefbdface06e9223f43f089556b9dcf104020fbc0a200f6863c57d4405', size: 11978867 },
  'tur:fast': { sha256: '7393381111e1152420fc4092cb44eef4237580d21b92bf30d7d221aad192c6b7', size: 4550554 },
  'tur:best': { sha256: 'e0c3338dc17503dc7d335a507c9ae01b2b46cfd07561171e1e1ac55d85e8e438', size: 7456265 },
  'vie:fast': { sha256: '79df64caf7bcfb2a27df5042ecb6121e196eada34da774956995747636d5bfa1', size: 531275 },
  'vie:best': { sha256: 'b6b49293d95d0b6dbd8780174627e82c75be957b6f4ed9862155540d6b00bb45', size: 12435550 },
  'ind:fast': { sha256: '69786901da87ab8766c1ea7fbb10b28f2110c14da3f6c8f2735df131fba95d88', size: 1122661 },
  'ind:best': { sha256: '1f6596041ffb4cd5094e5f98764db43cfde04edb8f02b988f90ebc1353ac73b8', size: 8253606 },
  'rus:fast': { sha256: 'e16e5e036cce1d9ec2b00063cf8b54472625b9e14d893a169e2b0dedeb4df225', size: 3861738 },
  'rus:best': { sha256: 'b617eb6830ffabaaa795dd87ea7fd251adfe9cf0efe05eb9a2e8128b7728d6b6', size: 15301764 },
  'ukr:fast': { sha256: 'd59e53e2bded32f4445f124b4b00240fcac7e8044c003ab822ccb94f0b3db59b', size: 3825102 },
  'ukr:best': { sha256: '1277f6e3b6f707063a92d40e7678e7f57154e8414e328e340be9ee9275eea9c8', size: 10859081 },
  'ell:fast': { sha256: '4fba8a0b461038d51f1c20d043d4f2ac38c4e778f1b90830847f7bd8fa3ba726', size: 1419514 },
  'ell:best': { sha256: '288b4ea00bab450cf39893d22f04a2835a8469b673b5b20dcb39b159d1bbc9b8', size: 8945021 },
  'heb:fast': { sha256: '11f9e43ab227f786352a50f75c94c2e9906f1baba86d93276da19da7ce0904db', size: 961404 },
  'heb:best': { sha256: 'dbaa827aea6bc21215638447f17783a1004987c2d0bf5573d111fee397abdae5', size: 3704077 },
  'ara:fast': { sha256: 'e3206d3dc87fd50c24a0fb9f01838615911d25168f4e64415244b67d2bb3e729', size: 1432056 },
  'ara:best': { sha256: 'ab9d157d8e38ca00e7e39c7d5363a5239e053f5b0dbdb3167dde9d8124335896', size: 12603724 },
  'fas:fast': { sha256: 'db1c0a91208aff00d3cf1ed2c1d23f76419afd5f024688b4f71adc3f2ce4a505', size: 431500 },
  'fas:best': { sha256: '99e420969b5ddd2cb135b416316a7ed417c59c4faf9e0d28941348f6448114df', size: 3325955 },
  'hin:fast': { sha256: '4c73ffc59d497c186b19d1e90f5d721d678ea6b2e277b719bee4e2af12271825', size: 1122751 },
  'hin:best': { sha256: 'bd2e65a2184af08a167b0be2439e91fa5edbc4394399ca2f692b843ae26e78d6', size: 11895564 },
  'ben:fast': { sha256: '31163084c279aaebd376216f0c3d5c17ad4b5fee8db49dae79c20000b5de5964', size: 855841 },
  'ben:best': { sha256: '1cd0129288d1f74f6661c35e638e487bd146a66bb732ecd9e011e48dcb0df623', size: 11045427 },
  'tam:fast': { sha256: 'd02fbec24be4b07e32e80d0ccfc3b6b67a3c5d61c9d0a7c8532677990912c6ec', size: 3237963 },
  'tam:best': { sha256: '4b9ce85987f629dd31eaf87443a1646452a43cdf91fcf05e017382ad595dcb9e', size: 6023201 },
  'tha:fast': { sha256: '294227cc2d1292b0acb28d61d4115c88252b96d466ca90b417cf4cf0c67bf07c', size: 1072600 },
  'tha:best': { sha256: 'ee8adab6dc69eb8df3d3c8307ae8295471b7bd7d86a06d9267aa8f479b064eac', size: 7614571 },
  'chi_sim:fast': { sha256: 'a5fcb6f0db1e1d6d8522f39db4e848f05984669172e584e8d76b6b3141e1f730', size: 2469156 },
  'chi_sim:best': { sha256: '4fef2d1306c8e87616d4d3e4c6c67faf5d44be3342290cf8f2f0f6e3aa7e735b', size: 13077423 },
  'chi_tra:fast': { sha256: '529c5b5797d64b126065cd55f2bb4c7fd7b15790798091b1ff259941a829330b', size: 2366642 },
  'chi_tra:best': { sha256: '1aa60488574cafa69486d919284f079ca9b68fcc7f6ad8dc1ff1b318dfd97028', size: 12985735 },
  'jpn:fast': { sha256: '1f5de9236d2e85f5fdf4b3c500f2d4926f8d9449f28f5394472d9e8d83b91b4d', size: 2471260 },
  'jpn:best': { sha256: '36bdf9ac823f5911e624c30d0553e890b8abc7c31a65b3ef14da943658c40b79', size: 14330109 },
  'kor:fast': { sha256: '6b85e11d9bbf07863b97b3523b1b112844c43e713df8b66418a081fd1060b3b2', size: 1677415 },
  'kor:best': { sha256: 'f888d4038348a0c3d25151e7f452bda0d74ca275b18cab146798bcbb94084fff', size: 12528128 },
}

export function digestFor(code: string, set: 'fast' | 'best'): PackDigest | undefined {
  return PACK_DIGESTS[`${code}:${set}`]
}
